name: Build Kernel
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
        kernel-url: https://github.com/LineageOS/android_kernel_xiaomi_sm8150.git
        kernel-branch: lineage-22.2
        config: vendor/sm8150-perf_defconfig
        arch: arm64
        aosp-clang: true
        anykernel3: true
        release: false